services:
  web:
    container_name: alpos_web
    image: alpos_web
    build:
      context: ./alpos-site-web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL="http://localhost:4000/"
    restart: always
    depends_on:
      - api
  api:
    container_name: alpos_api
    image: alpos_api
    build:
      context: ./alpos-site-api
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
  db:
    container_name: alpos_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
